test event be
Kelompok1Harisenin/event-management-be pull request #15
Opened 2023-08-18 14:17 UTC by BOcort

2023-08-21 01:59 UTC, jesslyn-ctrl requested changes

2023-08-21 01:59 UTC, jesslyn-ctrl commented on src/controllers/event.controller.js
> +  }
- kalau sudah pake catchAsync tidak perlu pakai try catch lg
- untuk logicnya apakah bisa ditaruh di service?
- untuk penamaan function sebaiknya menggunakan camel case `getevent` -> `getEvent`

2023-08-21 01:59 UTC, jesslyn-ctrl commented on src/controllers/event.controller.js
> +    const Eventtitle = req.params.title;
- untuk penamaan variable di javascript sebaiknya menggunakan camel case  `eventTitle` dan tidak menggunakan capital letter di depan (biasanya huruf capital digunakan untuk penamaan Class).

2023-08-21 01:59 UTC, jesslyn-ctrl commented on src/controllers/event.controller.js
> +    const data = await event.findOne({
untuk penggunaan method sperti `findAll, findOne`, dll yg berhubungan dengan fetch data di db sebaiknya masuk ke dalam repository (contoh dapat dilihat pada user/auth repository yg sudah ada)

2023-08-21 01:59 UTC, jesslyn-ctrl commented on src/controllers/event.controller.js
> +    const data = await event.findAll();
untuk penggunaan method sperti findAll, findOne, dll yg berhubungan dengan fetch data di db sebaiknya masuk ke dalam repository (contoh dapat dilihat pada user/auth repository yg sudah ada)

2023-08-21 01:59 UTC, jesslyn-ctrl commented on src/controllers/event.controller.js
> +      masssage: 'Get Data',
untuk message ini tidak perlu lagi, jadi hanya perlu send data yg sudah di get saja

2023-08-21 01:59 UTC, jesslyn-ctrl commented on src/models/event.model.js
> +    ettendeQuota: {
ini spertinya typo, seharusnya `attendeeQuota`

2023-08-21 01:59 UTC, jesslyn-ctrl commented on src/models/index.js
> +module.exports.event = require('./event.model');
untuk penamaan model sebaiknya disesuaikan dengan yang existing menggunakan huruf capital `event` -> `Event`

2023-08-21 01:59 UTC, jesslyn-ctrl commented on src/services/event.service.js
untuk logic pada controller bisa ditaruh disini ya

2023-08-30 05:21 UTC, jesslyn-ctrl requested changes

2023-08-30 05:21 UTC, jesslyn-ctrl commented on src/routes/v1/event.router.js
> +router.get('/:title', geteventByTitle);
untuk get eventnya better dibuat by id mas

2023-08-30 07:32 UTC, BOcort commented on src/controllers/event.controller.js
> +  }
maaf kak saya masih bingung kalau logicnyadi taruh di service saya error terus kak padahal export nya udah betul jadi nya saya taruh langsung controlller kak

2023-08-30 10:28 UTC, jesslyn-ctrl approved these changes

2023-08-30 10:29 UTC, merged